### ISSUE TITLE
Manual?

### ISSUE THREAD

**Issue by root-Rose** [noahbliss/Viper4Linux#31]
Is there a resource of some sort I could read up on to understand all the options that viper has to offer and what they mean/do?

**Comment by ThePBone** [comment]
If you use the GUI you can get more information about effects like this: 

1. Click on the button with the three dots
2. Choose 'context help' from the menu
3. Then click on the section you want to know more about

Otherwise, you can find more details here:
<http://fiio-instruction.fiio.net/VipersAudio%20Sound%20Effect%20Brief%20Introduction.pdf>

**Comment by noahbliss** [comment]
Thanks @ThePBone!

@root-Rose feel free to re-open if this doesn't fully answer your question. Thanks!
