### ISSUE TITLE
Volume change

### ISSUE THREAD

**Issue by Blank517** [noahbliss/Viper4Linux#8]
When I stop viper.sh the master volume rises to 100%

**Comment by L3vi47h4N** [comment]
Hey sorry @Blank517, are you using the statically set devices.conf or are you letting viper figure it out? Can I get that file, your logs in /tmp/viper4linux, and your Distro/DE information?

**Comment by Baerbeisser** [comment]
I had the same problem too a while ago.
When a video was already playing and i started viper, it gave first no sound, then after pausing the video some short noises, then it worked.
And lots of
```
WARNUNG: Von Element /GstPipeline:pipeline0/GstPulseSrc:pulsesrc0: Der Ton kann nicht schnell genug aufgezeichnet werden
Zusätzliche Fehlerdiagnoseinformation:
gstaudiobasesrc.c(849): gst_audio_base_src_create (): /GstPipeline:pipeline0/GstPulseSrc:pulsesrc0:
Dropped 12348 samples. This is most likely because downstream can't keep up and is consuming samples too slowly.
```
Just as i was about to generate some logfiles for you, the problem disappeared for a vew days. (cause of multiple starts/stops?)
I opened youtube today,  then started viper, then Bomi (audio/video-player) 
and the sound was on 100%, not changeable. And lots of dropped samples again. A restart of viper fixed it.

[viper.log](https://github.com/L3vi47h4N/Viper4Linux/files/2505848/viper.log)

**Comment by L3vi47h4N** [comment]
@baerbeisser that's an issue I occasionally have as well, the modification to pulseaudio to fix stuttering may help you. Otherwise, I'd recommend doing some independent searches to investigate "reducing pulseaudio latency" I've yet to find a solution for this problem that I can incorporate into viper. As for the volume issue, what desktop environment are you using?

**Comment by Baerbeisser** [comment]
Thanks, but i already applied that fix after i installed viper.
No, the problem is not latency. It seems, pulse with viper enabled doesn't always pick up new applications, and sets the volume on some hidden channel to max volume. And the no-sound-delay after starting viper, wich has gone away after starting and stopping viper multiple times.
Setup: XFCE4 with devices.conf on Artix (OpenRC fork of Arch) on AMD Ryzen 7 and Vega 56.

**Comment by L3vi47h4N** [comment]
@Baerbeisser I don't know what is causing your issue, but if you install pavucontrol you may be able ot gain some additional insight.
